# Generated by Django 5.2.5 on 2025-08-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_jobseekerprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='professional_summary',
            field=models.TextField(blank=True, help_text='A brief 2-3 sentence summary of your skills and career goals.', null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
