# Generated by Django 5.2.5 on 2025-09-18 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employerprofile_company_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='email',
        ),
    ]
