# Generated by Django 5.2.6 on 2025-10-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_jobseekerprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
