# Generated by Django 5.2.6 on 2025-11-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_jobseekerprofile_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company_bio',
            field=models.TextField(blank=True, help_text='Extended company biography for public profile', null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing'), ('Consulting', 'Consulting'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
