# Generated by Django 5.2.5 on 2025-09-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobposting_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='application_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
