# Generated by Django 5.2.5 on 2025-09-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_interview_interviewslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='scheduled_time',
            new_name='confirmed_slot',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='employer_notes',
        ),
        migrations.RemoveField(
            model_name='interviewslot',
            name='is_selected',
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_details',
            field=models.TextField(blank=True, help_text='e.g., Google Meet link, phone number, or office address.', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Approved for Interview', 'Approved for Interview'), ('Rejected', 'Rejected')], default='Submitted', max_length=50),
        ),
    ]
