# Generated by Django 5.2.5 on 2025-09-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_scheduled_time_interview_confirmed_slot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewslot',
            old_name='time',
            new_name='proposed_time',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
