# Generated by Django 5.2.6 on 2025-09-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_rename_time_interviewslot_proposed_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume_template',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('professional', 'Professional')], default='classic', max_length=20),
        ),
    ]
