# Generated by Django 5.2.6 on 2025-10-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobposting_updated_at_jobmatchscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview'), ('Offered', 'Offered'), ('Rejected', 'Rejected')], default='Submitted', max_length=50),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('Proposed', 'Proposed'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Proposed', max_length=20),
        ),
    ]
