# Generated by Django 5.2.6 on 2025-10-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_application_status_alter_interview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='vacancies',
            field=models.PositiveIntegerField(default=1, help_text='Number of available positions for this role.'),
        ),
    ]
