# Generated by Django 5.2.6 on 2025-11-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_jobposting_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='salary_max',
            field=models.IntegerField(blank=True, help_text='Maximum salary in USD', null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_min',
            field=models.IntegerField(blank=True, help_text='Minimum salary in USD', null=True),
        ),
    ]
