# Generated by Django 5.2.5 on 2025-09-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_achievement_description_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='issuing_organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='proficiency',
            field=models.CharField(blank=True, help_text='e.g., Expert, Intermediate, Beginner', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies_used',
            field=models.CharField(blank=True, help_text='Comma-separated list of technologies', max_length=255, null=True),
        ),
    ]
