# Generated by Django 5.2.5 on 2025-09-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_alter_language_proficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technologies_used',
        ),
        migrations.AddField(
            model_name='achievement',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='percentage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='aim',
            field=models.TextField(blank=True, help_text='A brief, 2-line aim of the project.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='backend',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='database',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='frontend',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Database', 'Database'), ('DevOps', 'DevOps'), ('Tools', 'Tools'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
