# Generated by Django 5.2.6 on 2025-10-03 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_resume_updated_at'),
        ('users', '0006_jobseekerprofile_linkedin_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedResumeCache',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.jobseekerprofile')),
                ('parsed_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
