# Generated by Django 5.2.6 on 2025-10-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0010_parsedresumecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='feedback',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
