# Generated by Django 5.2.6 on 2025-11-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0012_resumepdfgeneration'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='resumepdfgeneration',
            new_name='resumes_res_resume__4807cf_idx',
            old_name='resumes_res_resume__idx',
        ),
        migrations.RenameIndex(
            model_name='resumepdfgeneration',
            new_name='resumes_res_task_id_2414a7_idx',
            old_name='resumes_res_task_id_idx',
        ),
    ]
