"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import logging.config

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --- SECURITY SETTINGS ---

# SECRET_KEY is now loaded exclusively from the .env file.
# The application will not run without this key being set.
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# Validate SECRET_KEY is set (critical security check)
if not SECRET_KEY:
    raise ValueError(
        "DJANGO_SECRET_KEY environment variable is not set! "
        "This is required for security. Please set it in your .env file or environment variables."
    )

# GOOGLE_AI_API_KEY is also loaded from the .env file.
GOOGLE_AI_API_KEY = os.getenv("GOOGLE_AI_API_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 't')

# ALLOWED_HOSTS can be set as comma-separated list in environment variable
# If not set, automatically allow Railway domains
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else []
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS if host.strip()]

# If ALLOWED_HOSTS is empty, automatically allow Railway domains
# This works in both development and production for Railway deployments
if not ALLOWED_HOSTS:
    # Allow all Railway domains automatically
    # Django supports leading dots to match subdomains
    # This will match: *.railway.app, *.up.railway.app, etc.
    ALLOWED_HOSTS = ['.railway.app', '.up.railway.app']
    # Also add specific common Railway patterns
    ALLOWED_HOSTS.extend(['railway.app', 'up.railway.app'])

# Production Security Settings (only enabled when DEBUG=False)
if not DEBUG:
    # HTTPS Settings
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Cookie Security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    
    # Session Timeout Settings
    SESSION_COOKIE_AGE = 3600  # 1 hour (in seconds)
    SESSION_SAVE_EVERY_REQUEST = True  # Extend session on each request
    SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Expire session when browser closes
    
    # Content Security
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    
    # CSRF Trusted Origins (set via environment variable)
    # If not set, automatically allow Railway origins in production
    CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if os.getenv('CSRF_TRUSTED_ORIGINS') else []
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS if origin.strip()]
    
    # If CSRF_TRUSTED_ORIGINS is empty in production, try to detect Railway domain
    # Note: Django doesn't support wildcards in CSRF_TRUSTED_ORIGINS
    # Railway may provide RAILWAY_PUBLIC_DOMAIN or we can construct from ALLOWED_HOSTS
    if not CSRF_TRUSTED_ORIGINS:
        # Check if Railway provides the public domain
        railway_domain = os.getenv('RAILWAY_PUBLIC_DOMAIN') or os.getenv('RAILWAY_STATIC_URL')
        if railway_domain:
            # Ensure it starts with https://
            if not railway_domain.startswith('http'):
                railway_domain = f'https://{railway_domain}'
            CSRF_TRUSTED_ORIGINS = [railway_domain]
        # If ALLOWED_HOSTS is set with specific domains, use those for CSRF
        elif ALLOWED_HOSTS and ALLOWED_HOSTS != ['.railway.app', '.up.railway.app']:
            # Use the first allowed host (assuming it's the main domain)
            # Note: This is a fallback - ideally set CSRF_TRUSTED_ORIGINS explicitly
            main_host = ALLOWED_HOSTS[0]
            if not main_host.startswith('.'):
                CSRF_TRUSTED_ORIGINS = [f'https://{main_host}']
else:
    # Development settings (less strict for local development)
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# --- Gemini API Settings ---
# A central switch to enable or disable all Gemini features.
USE_GEMINI = os.getenv('USE_GEMINI', 'True').lower() in ('true', '1', 't')

# The specific model to use for Gemini API calls.
GEMINI_MODEL = os.getenv('GEMINI_MODEL', 'models/gemini-2.5-flash')

# --- Job Features Settings ---
# A central switch to enable or disable job-related features.
# When False (default): Shows "Coming Soon" banner and blocks all job feature access
# When True: Removes "Coming Soon" banner and enables full job feature access
JOBS_FEATURE_ENABLED = os.getenv('JOBS_FEATURE_ENABLED', 'False').lower() in ('true', '1', 't')


# --- LOGGING CONFIGURATION ---
# Provides more detailed output in the console to help with debugging.
LOG_LEVEL = os.getenv('DJANGO_LOG_LEVEL', 'INFO').upper()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[%(asctime)s] %(levelname)s %(name)s: %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for django-allauth
    
    # django-allauth apps (must be before local apps)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',

    # Local apps
    'pages',
    'users',
    'resumes',
    'jobs',

    # Third-party apps
    'crispy_forms',
    'crispy_tailwind',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required for django-allauth
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.notifications',
                'core.context_processors.jobs_feature_enabled',
            ],
        },
    },
]


WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use DATABASE_URL if provided (Railway, Heroku, etc.), otherwise use SQLite for development
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # Use dj-database-url to parse DATABASE_URL
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    # Fallback to SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Static files directories for development
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# WhiteNoise configuration for serving static files
# Using CompressedStaticFilesStorage instead of Manifest version for better compatibility
# The Manifest version requires collectstatic to run successfully, which can fail in some environments
if DEBUG:
    # In development, use default storage
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    # In production, use WhiteNoise with compression (no manifest required)
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# WhiteNoise additional configuration
# Note: WhiteNoise serves files from STATIC_ROOT by default
# If collectstatic fails, files in STATICFILES_DIRS won't be served automatically
# We ensure collectstatic runs at container startup as a fallback

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.CustomUser'

# django-allauth Configuration
AUTHENTICATION_BACKENDS = [
    # Django default authentication backend
    'django.contrib.auth.backends.ModelBackend',
    # django-allauth authentication backend
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Site ID for django-allauth (required)
SITE_ID = 1

# Allauth settings (using new format to avoid deprecation warnings)
ACCOUNT_ADAPTER = 'users.adapters.CustomAccountAdapter'  # Custom adapter for user-type based redirects
SOCIALACCOUNT_ADAPTER = 'users.adapters.CustomSocialAccountAdapter'  # Custom adapter for social account signups
ACCOUNT_LOGIN_METHODS = {'username', 'email'}  # Can login with username or email
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']  # Required fields for signup
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Set to 'mandatory' if you want email verification for signups
# Note: Password reset always requires email verification regardless of this setting
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_SIGNUP_REDIRECT_URL = 'home'  # Fallback, but adapter will override

# Password reset settings
ACCOUNT_PASSWORD_RESET_REQUIRE_EMAIL = True  # Require email for password reset

# Email Configuration (for password reset)
# For development, use console backend (emails printed to console)
# For production, configure SMTP settings via environment variables
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 't')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() in ('true', '1', 't')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '').strip()
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '').strip()
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@ai-resume-builder.com').strip()
SERVER_EMAIL = os.getenv('SERVER_EMAIL', DEFAULT_FROM_EMAIL).strip()
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '10'))  # 10 second timeout

# Email configuration diagnostics (for Railway logs)
# Using print() to ensure messages appear in Railway logs immediately
print("\n" + "="*60)
print("Email Configuration Check")
print("="*60)

if EMAIL_BACKEND == 'django.core.mail.backends.console.EmailBackend':
    print("⚠️  WARNING: Using console email backend - emails will NOT be sent")
    print("   ACTION: Set EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend in Railway Variables")
    print("   ACTION: Configure EMAIL_HOST_USER and EMAIL_HOST_PASSWORD in Railway Variables")
else:
    print(f"✅ Email backend configured: {EMAIL_BACKEND}")
    if EMAIL_HOST_USER:
        print(f"✅ Email host user configured: {EMAIL_HOST_USER}")
    else:
        print("⚠️  WARNING: EMAIL_HOST_USER NOT SET - emails will fail to send")
        print("   ACTION: Set EMAIL_HOST_USER in Railway Variables")
    
    if EMAIL_HOST_PASSWORD:
        print("✅ Email host password configured")
    else:
        print("⚠️  WARNING: EMAIL_HOST_PASSWORD NOT SET - emails will fail to send")
        print("   ACTION: Set EMAIL_HOST_PASSWORD in Railway Variables")
    
    print(f"✅ Email host: {EMAIL_HOST}")
    print(f"✅ Email port: {EMAIL_PORT}")
    print(f"✅ Email TLS: {EMAIL_USE_TLS}")
    print(f"✅ Default from email: {DEFAULT_FROM_EMAIL}")

print("="*60 + "\n")

# Note: Railway BLOCKS direct SMTP connections to Gmail and other email providers
# This is a Railway security policy to prevent spam/abuse - it applies to ALL plans
# 
# Why Railway blocks SMTP:
# - Security: Prevents spam/abuse from their infrastructure
# - Policy: All outbound SMTP ports are blocked
# - Reliability: Transactional email services are more reliable
#
# Your Options:
# 1. SendGrid (recommended - easiest): https://sendgrid.com/
#    - Free tier: 100 emails/day
#    - Set EMAIL_HOST=smtp.sendgrid.net
#    - Set EMAIL_PORT=587
#    - Set EMAIL_HOST_USER=apikey
#    - Set EMAIL_HOST_PASSWORD=your-sendgrid-api-key
#
# 2. Resend (modern API): https://resend.com/
#    - Free tier: 100 emails/day
#    - Uses HTTPS API (no SMTP needed)
#
# 3. Mailgun: https://mailgun.com/
#    - Free tier: 5,000 emails/month for 3 months
#
# 4. Gmail API (if you really want Gmail):
#    - Uses HTTPS API instead of SMTP
#    - More complex setup (OAuth credentials required)
#    - See docs/GMAIL_API_SETUP.md for instructions
#
# For production on Railway, set these environment variables:
# EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
# EMAIL_HOST=smtp.sendgrid.net (or your SMTP server)
# EMAIL_PORT=587
# EMAIL_USE_TLS=True
# EMAIL_HOST_USER=apikey (for SendGrid) or your-email@gmail.com
# EMAIL_HOST_PASSWORD=your-api-key (for SendGrid) or your-app-password (for Gmail)
# DEFAULT_FROM_EMAIL=noreply@yourdomain.com
# EMAIL_TIMEOUT=10

# Social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True  # Allow automatic signup for social accounts
SOCIALACCOUNT_EMAIL_REQUIRED = True  # Require email from social accounts
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # Social accounts don't need email verification (Google/GitHub already verified)
SOCIALACCOUNT_QUERY_EMAIL = True  # Request email from social provider
SOCIALACCOUNT_STORE_TOKENS = False  # Don't store OAuth tokens
# Note: The adapter (CustomSocialAccountAdapter) handles automatic connection of social accounts
# to existing users with matching emails in pre_social_login method

# Social Account Providers Configuration (django-allauth)
# Get OAuth credentials from environment variables
GOOGLE_OAUTH2_CLIENT_ID = os.getenv('GOOGLE_OAUTH2_CLIENT_ID', '').strip()
GOOGLE_OAUTH2_CLIENT_SECRET = os.getenv('GOOGLE_OAUTH2_CLIENT_SECRET', '').strip()
GITHUB_CLIENT_ID = os.getenv('GITHUB_CLIENT_ID', '').strip()
GITHUB_CLIENT_SECRET = os.getenv('GITHUB_CLIENT_SECRET', '').strip()

# Remove any http:// or https:// prefixes from Client ID if present
if GOOGLE_OAUTH2_CLIENT_ID:
    GOOGLE_OAUTH2_CLIENT_ID = GOOGLE_OAUTH2_CLIENT_ID.replace('http://', '').replace('https://', '').strip()
if GITHUB_CLIENT_ID:
    GITHUB_CLIENT_ID = GITHUB_CLIENT_ID.replace('http://', '').replace('https://', '').strip()

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': GOOGLE_OAUTH2_CLIENT_ID,
            'secret': GOOGLE_OAUTH2_CLIENT_SECRET,
            'key': ''
        }
    },
    'github': {
        'APP': {
            'client_id': GITHUB_CLIENT_ID,
            'secret': GITHUB_CLIENT_SECRET,
            'key': ''
        }
    }
}

# OAuth configuration validation (prints to stdout for Railway logs)
# This helps diagnose OAuth issues in Railway logs
# Using print() to ensure messages appear in Railway logs immediately
print("\n" + "="*60)
print("OAuth Configuration Check")
print("="*60)

if GOOGLE_OAUTH2_CLIENT_ID:
    # Validate Client ID format
    if GOOGLE_OAUTH2_CLIENT_ID.endswith('.apps.googleusercontent.com'):
        print(f"✅ Google OAuth Client ID configured: {GOOGLE_OAUTH2_CLIENT_ID[:30]}...")
    else:
        print(f"❌ Google OAuth Client ID format is INCORRECT: {GOOGLE_OAUTH2_CLIENT_ID[:50]}...")
        print("   ERROR: Client ID should end with .apps.googleusercontent.com")
        print("   ERROR: This will cause 'invalid_client' error!")
        print("   ERROR: Please check Railway variable GOOGLE_OAUTH2_CLIENT_ID")
else:
    print("⚠️  WARNING: Google OAuth Client ID NOT SET - Google login will not work")
    print("   ACTION: Set GOOGLE_OAUTH2_CLIENT_ID in Railway Variables")

if GOOGLE_OAUTH2_CLIENT_SECRET:
    print("✅ Google OAuth Client Secret configured")
else:
    print("⚠️  WARNING: Google OAuth Client Secret NOT SET - Google login will not work")
    print("   ACTION: Set GOOGLE_OAUTH2_CLIENT_SECRET in Railway Variables")

if GITHUB_CLIENT_ID:
    print(f"✅ GitHub OAuth Client ID configured: {GITHUB_CLIENT_ID[:20]}...")
else:
    print("⚠️  WARNING: GitHub OAuth Client ID NOT SET - GitHub login will not work")

if GITHUB_CLIENT_SECRET:
    print("✅ GitHub OAuth Client Secret configured")
else:
    print("⚠️  WARNING: GitHub OAuth Client Secret NOT SET - GitHub login will not work")

print("="*60 + "\n")

# Also log using Django logging (for completeness)
import logging
oauth_logger = logging.getLogger(__name__)

if GOOGLE_OAUTH2_CLIENT_ID:
    if GOOGLE_OAUTH2_CLIENT_ID.endswith('.apps.googleusercontent.com'):
        oauth_logger.info(f'Google OAuth Client ID configured: {GOOGLE_OAUTH2_CLIENT_ID[:30]}...')
    else:
        oauth_logger.error(f'Google OAuth Client ID format is INCORRECT: {GOOGLE_OAUTH2_CLIENT_ID[:50]}...')
        oauth_logger.error('Client ID should end with .apps.googleusercontent.com')
else:
    oauth_logger.warning('Google OAuth Client ID NOT SET')

if not GOOGLE_OAUTH2_CLIENT_SECRET:
    oauth_logger.warning('Google OAuth Client Secret NOT SET')

if not GITHUB_CLIENT_ID:
    oauth_logger.warning('GitHub OAuth Client ID NOT SET')

if not GITHUB_CLIENT_SECRET:
    oauth_logger.warning('GitHub OAuth Client Secret NOT SET')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
MAX_PROFILE_PHOTO_SIZE = 5 * 1024 * 1024  # 5MB
MAX_SCREENSHOT_SIZE = 10 * 1024 * 1024  # 10MB

LOGIN_URL = 'account_login'  # django-allauth login URL
LOGIN_REDIRECT_URL = 'home'

# Age Validation Settings
MIN_AGE = int(os.getenv('MIN_AGE', '18'))
MAX_AGE = int(os.getenv('MAX_AGE', '100'))

# AWS S3 Configuration for Media Files (Production)
USE_S3 = os.getenv('USE_S3', 'False').lower() in ('true', '1', 't')

if USE_S3:
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_DEFAULT_ACL = 'public-read'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    
    # Media files
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'


# Celery Configuration
# Read from environment variables, with fallback for backward compatibility
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Auto-configure pool based on platform
# Celery Worker Pool Configuration
# Note: Command-line -P flag overrides this setting
# We don't set CELERY_WORKER_POOL here to avoid conflicts
# Instead, we let Celery use its default (prefork) or the command-line argument
# This prevents the "worker_pool setting shouldn't be used" warning
import platform

# For Windows development, recommend solo pool in documentation
# For Linux/Mac production, use prefork pool (default) - most stable with Redis
# Eventlet is NOT recommended due to Redis connection errors
if platform.system() == 'Windows':
    # Windows: Don't set CELERY_WORKER_POOL, let command-line handle it
    # Default behavior: Use 'solo' pool via command-line argument
    pass
else:
    # Linux/Mac: Don't set CELERY_WORKER_POOL, let Celery use default (prefork)
    # This avoids the warning about worker_pool setting
    # Prefork is the default and most stable with Redis
    pass
